### ISSUE TITLE
ManageHistoryのDataGridの数値のソートがうまくいかない

### ISSUE THREAD

**Issue by keishi2006** [airanbuna/UmaTeamScores#1]
とても便利に使わせてもらってます！

掲題について、ManageHistory画面で、例えば順位でソートしたときに 1, 10, 11, ... , 15, 2, 3, ... という並びになることがわかりました。これはDataGrid内の数値に関するコンテンツすべてで共通の動作となっています。
![image](https://user-images.githubusercontent.com/85349119/120804816-07aa0200-c580-11eb-8339-cb4205211a6d.png)

順位ソートなどは割と頻繁に使用すると思うので、改善いただけると幸いです。

原因はおそらく、`ManageHistory.xaml.cs` の処理でDataGridに文字列で代入しているからかと思います。
~~例えば以下のコードのようにすると数値と文字列を混在できると思うので、ご検討ください。~~
~~https://gist.github.com/KentaYamada/9066065~~

**Comment by keishi2006** [comment]
すみません、色々と勘違いしていました。
DataGridではなくDataTableということで、[こちら](http://okwakatta.net/code/dst04.html) を参考に書き換えてみました。

```C#
private DataTable CreateDataTable()
// 略
    dt.Columns.Add("距離", Type.GetType("System.String"));
    dt.Columns.Add("ウマ", Type.GetType("System.String"));
    dt.Columns.Add("脚質", Type.GetType("System.String"));
    dt.Columns.Add("順位", Type.GetType("System.Int32"));
    dt.Columns.Add("平均", Type.GetType("System.Int32"));
// 略
    try
    {
        for (int i = 0; i < 21; i++)
        {
            DataRow row = dt.NewRow();
// 略
            row["距離"] = strtmp[0];
// 以下略
```

上記のとおりにしたところ、私が期待する通りにソートされました。
※順位はjsonを読んだナマの値を代入したので-7などが見えています。
![image](https://user-images.githubusercontent.com/85349119/120814577-fd8d0100-c589-11eb-9720-88897b1a3048.png)

ご参考まで。
設計意図に合わせてご対応いただけると幸いです。

**Comment by airanbuna** [comment]
対応させていただきました。
DataGrid周りはごちゃごちゃでよく分からない状態だったので情報をいただけて凄く助かりました。
ありがとうございます。
Releaseのzipを上げ直したので宜しければ更新をお願いします。

**Comment by keishi2006** [comment]
ご対応ありがとうございます！　とても使いやすくなりました :heart:
それでは、このissueクローズさせていただきます。

BOOTHだと古い版のようだったので、そちらも更新していただけると幸いです :thumbsup:
